# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Keeping Blessing Hill
email: joyce.sackett@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  'Keeping Blessing Hill is the story of how two very flawed people built a welcoming home out of a dilapidated barn, turned a wildly overgrown hill into a garden, and lived out a commitment to honor Christ in every aspect of their lives by opening their hearts to whatever God wanted to do. It turned out what God had in mind was “keeping”: keeping a house and garden, keeping an open door, keeping a strong marriage, and keeping devotion to those things that are eternal. Meditations about joy and glory and wonder mingle with practical household tips, recipes, and amusing stories about a family that knows how to keep life jolly as readers gain a fresh attentiveness to and perspective on God, nature, and relationships.'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.keepingblessinghill.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

collections:
  books:
    output: true
    permalink: /books/:title/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
